/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AteliersRouteImport } from './routes/ateliers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DiscoverySetRouteImport } from './routes/discovery-set'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GiftCardsRouteImport } from './routes/gift-cards'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as PressRouteImport } from './routes/press'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AteliersRoute = AteliersRouteImport.update({
  id: '/ateliers',
  path: '/ateliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverySetRoute = DiscoverySetRouteImport.update({
  id: '/discovery-set',
  path: '/discovery-set',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCardsRoute = GiftCardsRouteImport.update({
  id: '/gift-cards',
  path: '/gift-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ateliers': typeof AteliersRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discovery-set': typeof DiscoverySetRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/journal': typeof JournalRoute
  '/newsletter': typeof NewsletterRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/stores': typeof StoresRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ateliers': typeof AteliersRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discovery-set': typeof DiscoverySetRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/journal': typeof JournalRoute
  '/newsletter': typeof NewsletterRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/stores': typeof StoresRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ateliers': typeof AteliersRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/discovery-set': typeof DiscoverySetRoute
  '/faq': typeof FaqRoute
  '/gift-cards': typeof GiftCardsRoute
  '/journal': typeof JournalRoute
  '/newsletter': typeof NewsletterRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/returns': typeof ReturnsRoute
  '/shipping': typeof ShippingRoute
  '/stores': typeof StoresRoute
  '/sustainability': typeof SustainabilityRoute
  '/terms': typeof TermsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ateliers'
    | '/auth'
    | '/contact'
    | '/discovery-set'
    | '/faq'
    | '/gift-cards'
    | '/journal'
    | '/newsletter'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/stores'
    | '/sustainability'
    | '/terms'
    | '/collections/$slug'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ateliers'
    | '/auth'
    | '/contact'
    | '/discovery-set'
    | '/faq'
    | '/gift-cards'
    | '/journal'
    | '/newsletter'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/stores'
    | '/sustainability'
    | '/terms'
    | '/collections/$slug'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ateliers'
    | '/auth'
    | '/contact'
    | '/discovery-set'
    | '/faq'
    | '/gift-cards'
    | '/journal'
    | '/newsletter'
    | '/press'
    | '/privacy'
    | '/returns'
    | '/shipping'
    | '/stores'
    | '/sustainability'
    | '/terms'
    | '/collections/$slug'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AteliersRoute: typeof AteliersRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DiscoverySetRoute: typeof DiscoverySetRoute
  FaqRoute: typeof FaqRoute
  GiftCardsRoute: typeof GiftCardsRoute
  JournalRoute: typeof JournalRoute
  NewsletterRoute: typeof NewsletterRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ReturnsRoute: typeof ReturnsRoute
  ShippingRoute: typeof ShippingRoute
  StoresRoute: typeof StoresRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TermsRoute: typeof TermsRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ateliers': {
      id: '/ateliers'
      path: '/ateliers'
      fullPath: '/ateliers'
      preLoaderRoute: typeof AteliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discovery-set': {
      id: '/discovery-set'
      path: '/discovery-set'
      fullPath: '/discovery-set'
      preLoaderRoute: typeof DiscoverySetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-cards': {
      id: '/gift-cards'
      path: '/gift-cards'
      fullPath: '/gift-cards'
      preLoaderRoute: typeof GiftCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AteliersRoute: AteliersRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DiscoverySetRoute: DiscoverySetRoute,
  FaqRoute: FaqRoute,
  GiftCardsRoute: GiftCardsRoute,
  JournalRoute: JournalRoute,
  NewsletterRoute: NewsletterRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ReturnsRoute: ReturnsRoute,
  ShippingRoute: ShippingRoute,
  StoresRoute: StoresRoute,
  SustainabilityRoute: SustainabilityRoute,
  TermsRoute: TermsRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
